# Generated by Django 5.1.7 on 2025-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="published",
            field=models.DateTimeField(null=True),
        ),
    ]
