# Generated by Django 5.1.7 on 2025-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_insight_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="country",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insight",
            name="end_year",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="pestle",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insight",
            name="region",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insight",
            name="sector",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insight",
            name="source",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insight",
            name="start_year",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="topic",
            field=models.TextField(),
        ),
    ]
