# Generated by Django 5.1.7 on 2025-03-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_insight_country_alter_insight_end_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="start_year",
            field=models.TextField(blank=True, null=True),
        ),
    ]
