# Generated by Django 5.1.7 on 2025-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_insight_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="sector",
            field=models.TextField(null=True),
        ),
    ]
