# Generated by Django 5.1.7 on 2025-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_insight_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="country",
            field=models.TextField(null=True),
        ),
    ]
