# Generated by Django 5.1.7 on 2025-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_insight_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="insight",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="pestle",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="region",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="source",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="topic",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="url",
            field=models.TextField(null=True),
        ),
    ]
