# Generated by Django 5.1.7 on 2025-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_insight_insight_alter_insight_pestle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="added",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="intensity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="likelihood",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="relevance",
            field=models.IntegerField(null=True),
        ),
    ]
