# Generated by Django 5.1.7 on 2025-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_insight_added_alter_insight_intensity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="insight",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="insight",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="insight",
            name="url",
            field=models.TextField(default=""),
        ),
    ]
